add disconnect method
kuzzleio/kuzzle-plugin-mqtt pull request #5
Opened 2016-11-23 17:22 UTC by benoitvidis

refers to https://github.com/kuzzleio/kuzzle/issues/454

2016-11-24 10:53 UTC, scottinet requested changes

2016-11-24 10:53 UTC, scottinet commented on lib/index.js
> +  this.disconnect = function (clientId) {
Quickly checking mosca documentation, I think the `onConnection`method should also store the provided `client`object.
This allows the `disconnect` method to call `client.close([callback], [reason])`, actively closing the client's connection.

2016-11-24 10:59 UTC, scottinet approved these changes

2016-11-28 13:58 UTC, ballinette commented on test/docker-compose.yml
> +version: '2'
same remark as for https://github.com/kuzzleio/kuzzle-plugin-websocket/pull/7

2016-12-12 15:10 UTC, xbill82 approved these changes

2016-12-14 16:58 UTC, ballinette approved these changes

2016-12-14 16:58 UTC, merged